spring:
  sql:
    init:
      # https://stackoverflow.com/questions/38040572/spring-boot-loading-initial-data
      mode: always
  datasource:
    url: jdbc:h2:mem:springboot_security;MODE=MySQL
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none